#!/bin/sh

export LANG=C.UTF-8
export LC_ALL=C.UTF-8
export HOME="$(pwd)/debian/tests.home"
[ -e debian/tests.home ] || mkdir debian/tests.home
mkdir "$HOME"/.config || true

xvfb-run -a --server-args="-screen 0 1024x768x24+32" \
    Xephyr -reset -br -screen 1024x768 :2 & x_pid=$!

sleep 1
DISPLAY=:2 openbox & openbox_pid=$!
sleep 1

trap "pkill -TERM -P ${openbox_pid}; kill ${openbox_pid}; pkill -TERM -P ${x_pid}; kill ${x_pid}; rm -rf debian/tests.home" EXIT

DISPLAY=:2 dbus-launch --exit-with-session dh_auto_test
